### ISSUE TITLE
How will i add Network error message?

### ISSUE THREAD

**Issue by onyedika135** [SabithPkcMnr/WebViewMaster#2]
Please i have been trying to add Network error message if there's not internet access on the Phone. But i'm getting errors.
Help please i'm a novice in android programming
**Here's what i have been trying**
`           superWebView= (WebView) findViewById(R.id.webView);
           superWebView.setWebViewClient(new myWebClient());
           superWebView.getSettings().setJavaScriptEnabled(true);
           superWebView.loadUrl("http://google.com");
           superWebView.setWebViewClient(new WebViewClient() {
          public void onReceivedError(WebView webView, int errorCode, String description, String failingUrl) 
          {
            try {
                webView.stopLoading();
            } catch (Exception e) {
            }

            if (webView.canGoBack()) {
                webView.goBack();
            }

            webView.loadUrl("about:blank");
            AlertDialog alertDialog = new AlertDialog.Builder(MainActivity.this).create();
            alertDialog.setTitle("Error");
            alertDialog.setMessage("Check your internet connection and try again.");
            alertDialog.setButton(DialogInterface.BUTTON_POSITIVE, "Try Again", new 
            DialogInterface.OnClickListener() {
                public void onClick(DialogInterface dialog, int which) {
                    finish();
                    startActivity(getIntent());
                }
               });

            alertDialog.show();
            super.onReceivedError(webView, errorCode, description, failingUrl);
            }
            });

            public class myWebClient extends WebViewClient
          {
            @Override
          public void onPageStarted(WebView view, String url, Bitmap favicon) {
          super.onPageStarted(view, url, favicon);
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {

        view.loadUrl(url);
        return true;

          }
         }`

**Comment by SabithPkcMnr** [comment]
Have you tried something like this? You can call the **loadErrorPage();** inside the **onReceivedError** method of the Android WebView.

```public void loadErrorPage(WebView webview){
        if(webview!=null){

            String htmlData ="<html><body><div align=\"center\" >"This is the description for the load fail : "+description+"\nThe failed url is : "+failingUrl+"\n"</div></body>";

            webview.loadUrl("about:blank");
            webview.loadDataWithBaseURL(null,htmlData, "text/html", "UTF-8",null);
            webview.invalidate();

        }
    }
```
